# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CT5Wpw7dMsFPbV1nqKZgWmCEPq_G4hTK

Import Library
"""

import pandas as pd

import numpy as np

"""Import CSV as dataframe"""

df=pd.read_csv(r'https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/WhiteWineQuality.csv',sep=";")

"""Get first five row of Dataframe"""

df.head()

"""Get Information of dataframe"""

df.info()

"""Get summary statistics"""

df.describe()

df.shape

df['quality'].value_counts()

duplicate=df.duplicated().sum()

df.drop_duplicates(inplace=True)

"""Get shape of dataframe"""

df.shape

"""Get Unique value in y variables"""

df.quality.value_counts()

"""Define Y dependent and x independent"""

y=df['quality']

y.shape

y

"""Get Column Name"""

df.columns

x=df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']]

x

"""GET X VARIABLE STANDARDIZED"""

from sklearn.preprocessing import StandardScaler

ss=StandardScaler()

x=ss.fit_transform(x)

x

"""Get Train Test split"""

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,stratify=y,random_state=2529)

x_train.shape,x_test.shape,y_train.shape,y_test.shape

"""Get Model Train"""

from sklearn.svm import SVC

svc=SVC()

svc.fit(x_train,y_train)

"""Get Model Prediction

"""

y_pred=svc.predict(x_test)

y_pred

y_pred.shape

"""Get Model Evaluation"""

from sklearn.metrics import  confusion_matrix,classification_report

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

"""Get Future Prediction

Steps

1. Extract a random row using smaple function
2. separete x and y
3. Standarize x
4. Predict
"""

df_new=df.sample(1)

df_new

df_new.shape

x_new=df_new.drop(['quality'],axis=1)

x_new=ss.fit_transform(x_new)

y_pred_new=svc.predict(x_new)

y_pred_new



